import "./globals.css";
import { ThemeProvider } from "@mui/material";
import theme from "../theme/index";

export const metadata = {
  title: "Eden Pharmacy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
